// World of ClaudeCraft self-host launcher (Moon edition).
// Starts PostgreSQL, the Moon game server (port 8788), and a Node.js
// static-file server + API/WS proxy on the public port 8787.
// Compiled to a single executable via Node SEA.
import { spawn, spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { createReadStream } from 'node:fs';
import fs from 'node:fs';
import http from 'node:http';
import net from 'node:net';
import os from 'node:os';
import path from 'node:path';

const ROOT = process.env.WOC_HOST_ROOT || path.dirname(process.execPath);
const MOON_EXE = path.join(ROOT, 'moon-server', 'bin', 'moon.exe');
const MOON_ENTRY = 'woc/main.lua';
const MOON_CWD = path.join(ROOT, 'moon-server');
const PG_BIN = path.join(ROOT, 'postgres', 'bin');
const DIST_DIR = path.join(ROOT, 'dist');

function isDirWritable(dir) {
  try { fs.mkdirSync(dir, { recursive: true }); const p = path.join(dir, `.woc-${process.pid}.tmp`); fs.writeFileSync(p, ''); fs.rmSync(p, { force: true }); return true; }
  catch { return false; }
}
const DATA_ROOT = (() => {
  if (process.env.WOC_DATA_ROOT) return path.resolve(process.env.WOC_DATA_ROOT);
  if (isDirWritable(ROOT)) return ROOT;
  return path.join(process.env.LOCALAPPDATA || process.env.APPDATA || os.homedir(), 'World of ClaudeCraft');
})();
const PG_DATA = path.join(DATA_ROOT, 'data', 'pgdata');
const PG_LOG = path.join(DATA_ROOT, 'data', 'postgres.log');
const PG_PASSWORD_FILE = path.join(DATA_ROOT, 'data', 'postgres-password.txt');
const ENV_FILE = path.join(DATA_ROOT, '.env');

const PUBLIC_PORT = parsePort(process.env.WOC_GAME_PORT, 8787);
const MOON_PORT = parsePort(process.env.WOC_GATE_PORT, 8788);
const WS_PORT = parsePort(process.env.WOC_WS_PORT, MOON_PORT + 1);
const PG_PORT = parsePort(process.env.WOC_PG_PORT, 5433);
const DB_USER = 'eastbrook';
const DB_NAME = 'postgres';

// ---------- helpers ----------
function parsePort(v, def) { const n = Number.parseInt(String(v ?? ''), 10); return Number.isFinite(n) && n > 0 && n < 65536 ? n : def; }
function readGateCountFromConfig() {
  try {
    const p = path.join(ROOT, 'moon-server', 'woc', 'config.lua');
    const s = fs.readFileSync(p, 'utf8');
    const m = s.match(/M\.GATE_COUNT\s*=\s*(\d+)/);
    if (m) { const n = Number.parseInt(m[1], 10); if (n >= 1) return n; }
  } catch {}
  return 4;
}
function log(...args) { console.log(`[host]`, ...args); }
function fail(msg) { console.error(`[host]`, msg); process.exitCode = 1; }
function sleep(ms) { return new Promise((r) => setTimeout(r, ms)); }

// ---------- .env / password ----------
function ensureDataDir() { fs.mkdirSync(path.dirname(PG_DATA), { recursive: true }); fs.mkdirSync(PG_DATA, { recursive: true }); }
function writeEnvFile(password) {
  fs.writeFileSync(ENV_FILE, [
    '# Generated by World of ClaudeCraft Moon self-host launcher.',
    `DATABASE_URL=postgres://${DB_USER}:${password}@127.0.0.1:${PG_PORT}/${DB_NAME}`,
    `PORT=${MOON_PORT}`,
    `WOC_GATE_PORT=${MOON_PORT}`,
    `DB_POOL_MAX_CLIENTS=200`,
    `MAX_PLAYERS_PER_REALM=50000`,
    `REALM_NAME=Claudemoon`,
    `PUBLIC_ORIGIN=http://localhost:${PUBLIC_PORT}`,
    `NODE_ENV=production`,
    `EMAIL_PROVIDER=console`,
    `STATIC_DIR=${DIST_DIR}`,
    '',
  ].join('\n'));
  fs.writeFileSync(PG_PASSWORD_FILE, password, { mode: 0o600 });
}

// ---------- PostgreSQL ----------
function run(exe, args) {
  const r = spawnSync(exe, args, { stdio: 'inherit', encoding: 'utf8' });
  if (r.status !== 0) throw new Error(`${path.basename(exe)} exited ${r.status}`);
  return r;
}
function probePgPort() {
  return new Promise((ok) => { const s = net.connect({ host: '127.0.0.1', port: PG_PORT }); s.setTimeout(600); s.on('connect', () => { s.destroy(); ok(true); }); s.on('error', () => { s.destroy(); ok(false); }); s.on('timeout', () => { s.destroy(); ok(false); }); });
}
async function waitForPgReady(sec = 60) {
  const dl = Date.now() + sec * 1000;
  while (Date.now() < dl) { if (await probePgPort()) return true; await sleep(500); }
  return false;
}
function generatePassword() { return randomBytes(24).toString('hex'); }
function ensurePostgres() {
  ensureDataDir();
  if (!fs.existsSync(path.join(PG_DATA, 'PG_VERSION'))) {
    log('initializing PostgreSQL...');
    const pw = generatePassword();
    const pwFile = path.join(path.dirname(PG_DATA), 'pg-initpw.txt');
    fs.writeFileSync(pwFile, pw);
    run(path.join(PG_BIN, 'initdb.exe'), ['-D', PG_DATA, '-U', DB_USER, '--pwfile', pwFile, '-A', 'scram-sha-256', '-E', 'UTF8', '--locale=C', '-c', 'max_connections=500']);
    fs.rmSync(pwFile, { force: true });
    writeEnvFile(pw);
    log('PostgreSQL initialized.');
  }
  if (!fs.existsSync(ENV_FILE)) {
    try { const pw = fs.readFileSync(PG_PASSWORD_FILE, 'utf8').trim(); if (pw) writeEnvFile(pw); }
    catch { fs.rmSync(path.join(PG_DATA, 'PG_VERSION'), { force: true }); ensurePostgres(); }
  }
}
function startPostgres() {
  spawn(path.join(PG_BIN, 'pg_ctl.exe'), ['-D', PG_DATA, '-l', PG_LOG, '-o', `-p ${PG_PORT} -h 127.0.0.1`, 'start'], { stdio: 'inherit' });
}
function stopPostgres() { spawnSync(path.join(PG_BIN, 'pg_ctl.exe'), ['-D', PG_DATA, 'stop', '-m', 'fast'], { stdio: 'inherit' }); }
function readPassword() { try { return fs.readFileSync(PG_PASSWORD_FILE, 'utf8').trim(); } catch { return ''; } }

// ---------- Moon server ----------
function waitForMoon(sec = 90) {
  return new Promise((ok) => {
    const dl = Date.now() + sec * 1000;
    const tryOnce = () => {
      const req = http.get(`http://127.0.0.1:${MOON_PORT}/health`, (res) => { res.resume(); if (res.statusCode === 200) return ok(true); retry(); });
      req.setTimeout(1500, () => { req.destroy(); retry(); });
      req.on('error', () => retry());
    };
    const retry = () => { if (Date.now() >= dl) return ok(false); setTimeout(tryOnce, 800); };
    tryOnce();
  });
}

// ---------- firewall ----------
function addFirewallRule(ports) {
  for (const port of ports) {
    spawnSync('netsh.exe', ['advfirewall', 'firewall', 'add', 'rule', `name=World of ClaudeCraft Moon (self-host) ${port}`, 'dir=in', 'action=allow', 'protocol=TCP', `localport=${port}`, 'profile=private,domain'], { stdio: 'ignore', windowsHide: true });
  }
}
function lanUrls() {
  const urls = [];
  for (const list of Object.values(os.networkInterfaces())) for (const iface of list || []) if (iface.family === 'IPv4' && !iface.internal) urls.push(`http://${iface.address}:${PUBLIC_PORT}`);
  return urls;
}

// ---------- Static file + proxy server ----------
const MIME = {
  '.html': 'text/html', '.css': 'text/css', '.js': 'text/javascript', '.mjs': 'text/javascript',
  '.json': 'application/json', '.xml': 'application/xml', '.txt': 'text/plain',
  '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png', '.gif': 'image/gif',
  '.webp': 'image/webp', '.svg': 'image/svg+xml', '.ico': 'image/x-icon',
  '.mp3': 'audio/mpeg', '.ogg': 'audio/ogg', '.wav': 'audio/wav', '.mp4': 'video/mp4', '.webm': 'video/webm',
  '.woff': 'application/font-woff', '.woff2': 'application/font-woff2',
  '.ttf': 'application/x-font-ttf', '.wasm': 'application/wasm',
  '.glb': 'model/gltf-binary', '.hdr': 'image/vnd.radiance',
  '.webmanifest': 'application/manifest+json',
  '.md': 'text/markdown; charset=utf-8', '.pdf': 'application/pdf',
};

function serveFile(res, filePath, cacheHint) {
  if (!fs.existsSync(filePath)) return false;
  const stat = fs.statSync(filePath);
  if (!stat.isFile()) return false;
  const mime = MIME[path.extname(filePath).toLowerCase()] || 'application/octet-stream';
  res.writeHead(200, {
    'Content-Type': mime, 'Content-Length': stat.size,
    'Cache-Control': cacheHint || 'public, max-age=3600',
    'Access-Control-Allow-Origin': '*',
  });
  createReadStream(filePath).pipe(res);
  return true;
}

function proxyToMoon(req, res) {
  const opts = {
    hostname: '127.0.0.1', port: MOON_PORT, path: req.url, method: req.method,
    headers: { ...req.headers, host: `127.0.0.1:${MOON_PORT}`, connection: 'close' },
  };
  delete opts.headers['transfer-encoding'];
  const proxyReq = http.request(opts, (proxyRes) => {
    res.writeHead(proxyRes.statusCode, proxyRes.headers);
    proxyRes.pipe(res);
  });
  proxyReq.on('error', () => { if (!res.headersSent) { res.writeHead(502); res.end(); } });
  if (['POST', 'PUT', 'PATCH'].includes(req.method)) {
    const body = []; req.on('data', (d) => body.push(d)); req.on('end', () => { proxyReq.write(Buffer.concat(body)); proxyReq.end(); });
  } else { req.resume(); proxyReq.end(); }
}

const indexFile = path.join(DIST_DIR, 'index.html');

function handleStaticRequest(req, res) {
  if (req.url?.startsWith('/api/') || req.url === '/health') return proxyToMoon(req, res);
  const urlPath = (() => { try { return new URL(req.url ?? '/', `http://${req.headers.host}`).pathname; } catch { return '/'; } })();
  const safe = path.resolve(path.join(DIST_DIR, urlPath === '/' ? 'index.html' : `.${urlPath}`));
  if (!safe.startsWith(path.resolve(DIST_DIR))) { res.writeHead(403); res.end(); return; }
  const cache = urlPath.startsWith('/assets/') ? 'public, max-age=31536000, immutable' : 'public, max-age=3600';
  if (serveFile(res, safe, cache)) return;
  serveFile(res, indexFile, 'no-cache');
}

// ---------- main ----------
async function main() {
  log(`World of ClaudeCraft (Moon) self-host launcher`);
  log(`root: ${ROOT}  data: ${DATA_ROOT}`);
  log(`public: ${PUBLIC_PORT}  moon: ${MOON_PORT}  pg: ${PG_PORT}`);

  for (const f of [MOON_EXE, path.join(PG_BIN, 'postgres.exe')]) { if (!fs.existsSync(f)) { fail(`missing: ${f}`); process.exit(1); } }
  if (!fs.existsSync(path.join(DIST_DIR, 'index.html'))) { fail(`dist/index.html missing`); process.exit(1); }

  ensurePostgres();
  if (!(await probePgPort())) { startPostgres(); if (!(await waitForPgReady())) { fail(`PG not ready`); return; } }

  log('starting Moon server...');
  const cpuCount = Number.parseInt(process.env.NUMBER_OF_PROCESSORS ?? '', 10) || os.cpus().length;
  const worldShards = Number.parseInt(process.env.WOC_WORLD_SHARDS ?? '', 10) || Math.max(1, Math.min(Math.floor(cpuCount / 2), 64));
  // Gate 实例数只以 config.lua 的 M.GATE_COUNT 为准 (改 config.lua 即可, 无需重新打包 launcher)
  const gateCount = readGateCountFromConfig();
  const threadCount = Number.parseInt(process.env.WOC_THREADS ?? '', 10) || (5 + worldShards + (gateCount - 1));
  const dbPoolSize = Number.parseInt(process.env.DB_POOL_SIZE ?? '', 10) || Math.max(8, Math.min(cpuCount * 4, 64));
  log(`adaptive threads: cpu=${cpuCount} threads=${threadCount} worldShards=${worldShards} gates=${gateCount} dbPool=${dbPoolSize}`);
  const moonProc = spawn(MOON_EXE, [MOON_ENTRY], {
    cwd: MOON_CWD,
    env: { ...process.env, DATABASE_URL: `postgres://${DB_USER}:${readPassword()}@127.0.0.1:${PG_PORT}/${DB_NAME}`, PORT: String(MOON_PORT), WOC_GATE_PORT: String(MOON_PORT), WOC_WS_PORT: String(WS_PORT), WOC_GATE_COUNT: String(gateCount), WOC_SHARDS: String(worldShards), WOC_REALM: 'Claudemoon', WOC_THREADS: String(threadCount), WOC_WORLD_SHARDS: String(worldShards), DB_POOL_SIZE: String(dbPoolSize), STATIC_DIR: DIST_DIR },
    stdio: 'inherit', windowsHide: true,
  });
  moonProc.on('error', (e) => fail(`moon: ${e.message}`));
  moonProc.on('exit', (c) => { log(`moon exited (${c})`); process.exitCode = c ?? 1; });

  if (!(await waitForMoon())) { fail(`moon not ready`); return; }

  const proxyServer = http.createServer(handleStaticRequest);

  // WebSocket upgrade proxy → 轮询到各 gate 的 WS 端口 (WOC_WS_PORT + 2k, 默认 8789/8791/...)
  // 黑洞连接防护: 任一端关闭/出错都显式销毁另一端 (不依赖 pipe 默认只在干净 FIN 时才互关),
  // 加 connect 超时与 TCP keepalive, 使静默掉线 (无 FIN/RST) 的死连接也能被回收,
  // 避免 socket 在代理与 moon 两侧累积到 moon 停止接受新连接 (此前只能重启恢复)。
  let wsRoundRobin = 0;
  proxyServer.on('upgrade', (req, socket, head) => {
    const targetPort = WS_PORT + 2 * ((wsRoundRobin++) % gateCount);
    let moon;
    let connectTimer;
    let tornDown = false;
    const teardown = () => {
      if (tornDown) return;
      tornDown = true;
      if (connectTimer) clearTimeout(connectTimer);
      socket.destroy();
      if (moon) moon.destroy();
    };
    socket.on('error', teardown);
    socket.on('close', teardown);
    socket.on('end', teardown);
    socket.setKeepAlive(true, 30_000);
    connectTimer = setTimeout(teardown, 10_000);
    moon = net.connect(targetPort, '127.0.0.1', () => {
      if (tornDown) return;
      clearTimeout(connectTimer);
      const lines = [`${req.method} ${req.url} HTTP/1.1`];
      const hdrs = { ...req.headers, host: `127.0.0.1:${targetPort}`, connection: 'Upgrade' };
      for (const [k, v] of Object.entries(hdrs)) { if (v !== undefined) lines.push(`${k}: ${v}`); }
      lines.push('', '');
      moon.write(lines.join('\r\n'));
      if (head.length > 0) moon.write(head);
      socket.pipe(moon);
      moon.pipe(socket);
    });
    moon.on('error', teardown);
    moon.on('close', teardown);
    moon.setKeepAlive(true, 30_000);
  });

  proxyServer.listen(PUBLIC_PORT, () => {
    // 放行 8787 (静态+/api) + 所有 gate 的 WS 端口 (8789+2k), 供浏览器直连
    const wsPorts = Array.from({ length: gateCount }, (_, k) => WS_PORT + 2 * k);
    addFirewallRule([PUBLIC_PORT, ...wsPorts]);
    log(`UP.`);
    log(`local:    http://localhost:${PUBLIC_PORT}`);
    for (const u of lanUrls()) log(`lan:      ${u}`);
    log(`ws direct: ${wsPorts.join(', ')} (browser connects straight to gates)`);
    log(`register, create character, enter the world.`);
    log(`Ctrl+C to stop.`);
  });

  const shutdown = async () => {
    proxyServer.close();
    if (moonProc && !moonProc.killed) { log('stopping moon...'); moonProc.kill(); }
    stopPostgres(); process.exit(0);
  };
  process.on('SIGINT', () => shutdown());
  process.on('SIGTERM', () => shutdown());
}

main().catch((err) => { console.error('[host] FATAL:', err); process.exit(1); });
