// World of ClaudeCraft self-host launcher. Compiled to a single executable via
// Node SEA (scripts/selfhost/package_host.mjs). Launches the bundled portable
// PostgreSQL, then the authoritative game server, and opens the game in the
// default browser. Intended for LAN play: http://<host-ip>:8787.
import { spawn, spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import fs from 'node:fs';
import http from 'node:http';
import net from 'node:net';
import os from 'node:os';
import path from 'node:path';

// The launcher is a SEA executable; process.execPath is the exe itself and the
// payload (node.exe, dist-server/, dist/, postgres/) sits next to it.
const ROOT = process.env.WOC_HOST_ROOT || path.dirname(process.execPath);
const BIN_DIR = path.join(ROOT, 'node.exe');
const SERVER_CJS = path.join(ROOT, 'dist-server', 'server.cjs');
const PG_BIN = path.join(ROOT, 'postgres', 'bin');

// Mutable state (.env, the PostgreSQL data dir, logs) must NOT live under a
// read-only install directory. Use the exe directory when it is writable
// (portable layout), otherwise fall back to the user's local app data.
function isDirWritable(dir) {
  try {
    fs.mkdirSync(dir, { recursive: true });
    const probe = path.join(dir, `.woc-write-${process.pid}.tmp`);
    fs.writeFileSync(probe, '');
    fs.rmSync(probe, { force: true });
    return true;
  } catch {
    return false;
  }
}
const DATA_ROOT = (() => {
  if (process.env.WOC_DATA_ROOT) return path.resolve(process.env.WOC_DATA_ROOT);
  if (isDirWritable(ROOT)) return ROOT;
  return path.join(process.env.LOCALAPPDATA || process.env.APPDATA || os.homedir(), 'World of ClaudeCraft');
})();
const PG_DATA = path.join(DATA_ROOT, 'data', 'pgdata');
const PG_LOG = path.join(DATA_ROOT, 'data', 'postgres.log');
const PG_PASSWORD_FILE = path.join(DATA_ROOT, 'data', 'postgres-password.txt');
const ENV_FILE = path.join(DATA_ROOT, '.env');

const GAME_PORT = parsePort(process.env.WOC_GAME_PORT, 8787);
const PG_PORT = parsePort(process.env.WOC_PG_PORT, 5433);
const DB_USER = 'eastbrook';
const DB_NAME = 'postgres'; // initdb always creates the maintenance database.

for (const file of [BIN_DIR, SERVER_CJS, path.join(PG_BIN, 'postgres.exe')]) {
  if (!fs.existsSync(file)) {
    console.error(`[host] missing bundled file: ${file}`);
    process.exit(1);
  }
}

// ---------- console helpers ----------
function log(...args) {
  console.log(`[host]`, ...args);
}
function fail(message) {
  console.error(`[host] FAILED: ${message}`);
  process.exitCode = 1;
}

// ---------- paths / state ----------
function ensureDataDir() {
  fs.mkdirSync(path.dirname(PG_DATA), { recursive: true });
  fs.mkdirSync(PG_DATA, { recursive: true });
}

function writeEnvFile(password) {
  fs.writeFileSync(
    ENV_FILE,
    [
      '# Generated by World of ClaudeCraft self-host launcher. Do not share.',
      `DATABASE_URL=postgres://${DB_USER}:${password}@127.0.0.1:${PG_PORT}/${DB_NAME}`,
      `PORT=${GAME_PORT}`,
      `DB_POOL_MAX_CLIENTS=40`,
      `MAX_PLAYERS_PER_REALM=2000`,
      `REALM_NAME=Claudemoon`,
      `PUBLIC_ORIGIN=http://localhost:${GAME_PORT}`,
      `NODE_ENV=production`,
      `EMAIL_PROVIDER=console`,
      ``,
    ].join('\n'),
  );
  fs.writeFileSync(PG_PASSWORD_FILE, password, { mode: 0o600 });
}

// ---------- PostgreSQL lifecycle ----------
function run(exe, args) {
  log(`run ${path.basename(exe)} ${args.join(' ')}`);
  const res = spawnSync(exe, args, { stdio: 'inherit', encoding: 'utf8' });
  if (res.status !== 0) {
    throw new Error(
      `${path.basename(exe)} exited ${res.status}: ${(res.stderr || res.stdout || '').toString().slice(-400)}`,
    );
  }
  return res;
}

function probePgPort() {
  return new Promise((resolve) => {
    const sock = net.connect({ host: '127.0.0.1', port: PG_PORT });
    sock.setTimeout(600);
    sock.on('connect', () => {
      sock.destroy();
      resolve(true);
    });
    sock.on('error', () => {
      sock.destroy();
      resolve(false);
    });
    sock.on('timeout', () => {
      sock.destroy();
      resolve(false);
    });
  });
}

async function waitForPgReady(seconds = 60) {
  const deadline = Date.now() + seconds * 1000;
  while (Date.now() < deadline) {
    if (await probePgPort()) return true;
    await sleep(500);
  }
  return false;
}

function generatePassword() {
  return randomBytes(24).toString('hex');
}

function ensurePostgres() {
  ensureDataDir();
  const initialized = fs.existsSync(path.join(PG_DATA, 'PG_VERSION'));
  if (initialized) return;
  log('initializing PostgreSQL data directory...');
  const pwFile = path.join(path.dirname(PG_DATA), 'pg-initpw.txt');
  const password = generatePassword();
  fs.writeFileSync(pwFile, password);
  run(path.join(PG_BIN, 'initdb.exe'), [
    '-D',
    PG_DATA,
    '-U',
    DB_USER,
    '--pwfile',
    pwFile,
    '-A',
    'scram-sha-256',
    '-E',
    'UTF8',
    '--locale=C',
    '-N',
    '200',
  ]);
  fs.rmSync(pwFile, { force: true });
  writeEnvFile(password);
  log('PostgreSQL initialized, .env written.');
}

function startPostgres() {
  log('starting PostgreSQL...');
  // stdio: 'inherit' (NOT detached/windowsHide) so pg_ctl and the postmaster it
  // launches attach to this launcher's console instead of opening their own
  // black console window. When the launcher window closes, Windows sends
  // CTRL_CLOSE to every attached process and postgres shuts down cleanly, so
  // closing the window really does stop the server. Postgres output still goes
  // to the -l log file, not the screen.
  const child = spawn(
    path.join(PG_BIN, 'pg_ctl.exe'),
    [
      '-D',
      PG_DATA,
      '-l',
      PG_LOG,
      '-o',
      `-p ${PG_PORT} -h 127.0.0.1`,
      'start',
    ],
    { stdio: 'inherit' },
  );
  child.on('error', (err) => {
    fail(`pg_ctl failed: ${err.message}`);
  });
  return child;
}

function stopPostgres() {
  log('stopping PostgreSQL...');
  spawnSync(path.join(PG_BIN, 'pg_ctl.exe'), ['-D', PG_DATA, 'stop', '-m', 'fast'], {
    stdio: 'inherit',
  });
}

// ---------- game server ----------
function startGameServer() {
  return new Promise((resolve, reject) => {
    log('starting game server...');
    // cwd = DATA_ROOT so process.loadEnvFile() finds the generated .env; the
    // server's static dir and bundle paths are __dirname-relative, not cwd-relative.
    const child = spawn(BIN_DIR, [SERVER_CJS], {
      cwd: DATA_ROOT,
      env: { ...process.env },
      stdio: 'inherit',
      windowsHide: true,
    });
    child.on('error', reject);
    child.on('exit', (code) => {
      log(`game server exited (${code})`);
      process.exitCode = code ?? 1;
    });
    resolve(child);
  });
}

function waitForGameHttp(seconds = 90) {
  return new Promise((resolve) => {
    const deadline = Date.now() + seconds * 1000;
    const tryOnce = () => {
      const req = http.get(
        `http://127.0.0.1:${GAME_PORT}/livez`,
        (res) => {
          res.resume();
          if (res.statusCode === 200) return resolve(true);
          retry();
        },
      );
      req.setTimeout(1500, () => {
        req.destroy();
        retry();
      });
      req.on('error', () => retry());
    };
    const retry = () => {
      if (Date.now() >= deadline) return resolve(false);
      setTimeout(tryOnce, 1000);
    };
    tryOnce();
  });
}

// ---------- firewall ----------
function addFirewallRule() {
  const rule = 'World of ClaudeCraft (self-host)';
  const res = spawnSync(
    'netsh.exe',
    [
      'advfirewall',
      'firewall',
      'add',
      'rule',
      `name=${rule}`,
      'dir=in',
      'action=allow',
      'protocol=TCP',
      `localport=${GAME_PORT}`,
      'profile=private,domain',
    ],
    { stdio: 'ignore', windowsHide: true },
  );
  log(res.status === 0 ? 'firewall rule added' : 'firewall rule skipped (run as admin for LAN access)');
}

function lanUrls() {
  const urls = [];
  for (const list of Object.values(os.networkInterfaces())) {
    for (const iface of list || []) {
      if (iface.family === 'IPv4' && !iface.internal) {
        urls.push(`http://${iface.address}:${GAME_PORT}`);
      }
    }
  }
  return urls;
}

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

// ---------- main ----------
async function main() {
  log(`World of ClaudeCraft self-host launcher`);
  log(`root: ${ROOT}`);
  log(`data: ${DATA_ROOT}`);
  log(`game port: ${GAME_PORT}, postgres port: ${PG_PORT}`);

  ensurePostgres();

  const alreadyUp = await probePgPort();
  if (!alreadyUp) {
    startPostgres();
    if (!(await waitForPgReady())) {
      fail(`PostgreSQL did not become ready on 127.0.0.1:${PG_PORT}. See ${PG_LOG}`);
      return;
    }
  }

  const server = await startGameServer();
  const live = await waitForGameHttp();
  if (!live) {
    fail(`game server did not answer /livez on port ${GAME_PORT}.`);
    return;
  }

  addFirewallRule();

  const urls = lanUrls();
  log(`server is UP.`);
  log(`local:    http://localhost:${GAME_PORT}`);
  for (const u of urls) log(`lan:      ${u}`);
  log(`register an account, then create a character and enter the world.`);
  log(`close this window to shut the server down.`);

  const shutdown = async () => {
    if (server && !server.killed) {
      log('stopping game server...');
      server.kill();
    }
    stopPostgres();
    process.exit(0);
  };
  process.on('SIGINT', () => shutdown());
  process.on('SIGTERM', () => shutdown());
  process.stdin.setRawMode?.(true);
  process.stdin.on('data', (chunk) => {
    if (String(chunk).toLowerCase().includes('q')) void shutdown();
  });
}

function parsePort(value, def) {
  const n = Number.parseInt(String(value ?? ''), 10);
  return Number.isFinite(n) && n > 0 && n < 65536 ? n : def;
}

main().catch((err) => {
  console.error('[host] FATAL:', err);
  process.exit(1);
});
